"use client";

import * as React from "react";
import { LayoutPanelTop, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { updateLayoutSettings } from "@/lib/actions/index";
import type { LayoutSettings } from "@/lib/layout-settings";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export function LayoutManager({ initial, ecommerce }: { initial: LayoutSettings; ecommerce: boolean }) { const [pending, startTransition] = React.useTransition(); return <form onSubmit={(event) => { event.preventDefault(); startTransition(async () => { try { await updateLayoutSettings(new FormData(event.currentTarget)); toast.success("Header and footer settings saved."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save layout settings."); } }); }} className="space-y-6"><div><h1 className="font-heading text-3xl font-semibold">Header & Footer</h1><p className="mt-1 text-sm text-muted-foreground">Control the shared layout for this tenant&apos;s storefront.</p></div><Card><CardHeader><CardTitle className="flex items-center gap-2 font-heading"><LayoutPanelTop className="size-4" />Header</CardTitle><CardDescription>Navigation links are managed separately in Navigation.</CardDescription></CardHeader><CardContent className="grid gap-3"> <Toggle name="headerVisible" label="Show header" defaultChecked={initial.headerVisible} /><Toggle name="headerSticky" label="Keep header visible while scrolling" defaultChecked={initial.headerSticky} /><Toggle name="headerShowCart" label="Show cart in header" defaultChecked={initial.headerShowCart} disabled={!ecommerce} /></CardContent></Card><Card><CardHeader><CardTitle className="font-heading">Footer</CardTitle><CardDescription>Choose which shared footer sections appear across this tenant&apos;s pages.</CardDescription></CardHeader><CardContent className="grid gap-3"><Toggle name="footerVisible" label="Show footer" defaultChecked={initial.footerVisible} /><Toggle name="footerShowBrand" label="Show brand and tagline" defaultChecked={initial.footerShowBrand} /><Toggle name="footerShowNavigation" label="Show navigation links" defaultChecked={initial.footerShowNavigation} /><Toggle name="footerShowContact" label="Show contact details" defaultChecked={initial.footerShowContact} /><Toggle name="footerShowHours" label="Show hours and business details" defaultChecked={initial.footerShowHours} /></CardContent></Card><Button disabled={pending}>{pending && <Loader2 className="mr-2 size-4 animate-spin" />}Save layout</Button></form>; }
function Toggle({ name, label, defaultChecked, disabled }: { name: string; label: string; defaultChecked: boolean; disabled?: boolean }) { return <label className="flex items-center justify-between gap-4 rounded-lg border p-3 text-sm font-medium"><span>{label}{disabled && <span className="ml-2 text-xs font-normal text-muted-foreground">Ecommerce template only</span>}</span><input name={name} type="checkbox" defaultChecked={defaultChecked} disabled={disabled} /></label>; }
