"use client";

import * as React from "react";
import { Pencil, Plus, Tags, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createPromotion, deletePromotion, updatePromotion } from "@/lib/actions/index";
import type { Promotion } from "@/lib/db/schema";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export function PromotionManager({ promotions }: { promotions: Promotion[] }) {
  const router = useRouter();
  const [editing, setEditing] = React.useState<Promotion | null | undefined>();
  const [pending, startTransition] = React.useTransition();
  function save(formData: FormData) { startTransition(async () => { try { if (editing) await updatePromotion(editing.id, formData); else await createPromotion(formData); toast.success(editing ? "Promotion updated." : "Promotion created."); setEditing(undefined); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save promotion."); } }); }
  function remove(promotion: Promotion) { if (!window.confirm(`Delete ${promotion.code}?`)) return; startTransition(async () => { try { await deletePromotion(promotion.id); toast.success("Promotion deleted."); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to delete promotion."); } }); }
  return <div className="space-y-6"><div className="flex items-end justify-between gap-4"><div><h1 className="font-heading text-3xl font-semibold">Promotions</h1><p className="mt-1 text-sm text-muted-foreground">Create scheduled coupon codes with customer and catalog eligibility rules.</p></div><Button onClick={() => setEditing(null)}><Plus className="mr-2 size-4" />New promotion</Button></div><Card><CardHeader><CardTitle className="font-heading">Discount codes</CardTitle><CardDescription>{promotions.length} configured promotion{promotions.length === 1 ? "" : "s"}.</CardDescription></CardHeader><CardContent className="px-0 pb-0">{promotions.length ? <Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Type</TableHead><TableHead>Status</TableHead><TableHead>Schedule</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{promotions.map((promotion) => <TableRow key={promotion.id}><TableCell><p className="font-medium">{promotion.code}</p><p className="text-xs text-muted-foreground">{promotion.name}</p></TableCell><TableCell>{promotionLabel(promotion)}</TableCell><TableCell><Badge variant={promotion.status === "active" ? "default" : "secondary"}>{promotion.status}</Badge></TableCell><TableCell className="text-xs text-muted-foreground">{scheduleLabel(promotion)}</TableCell><TableCell><div className="flex justify-end gap-1"><Button size="icon-sm" variant="ghost" onClick={() => setEditing(promotion)}><Pencil /></Button><Button size="icon-sm" variant="ghost" className="text-destructive" disabled={pending} onClick={() => remove(promotion)}><Trash2 /></Button></div></TableCell></TableRow>)}</TableBody></Table> : <div className="flex flex-col items-center gap-3 py-12 text-center"><Tags className="size-8 text-muted-foreground" /><p className="text-sm text-muted-foreground">No promotions yet.</p></div>}</CardContent></Card><Dialog open={editing !== undefined} onOpenChange={(open) => !open && setEditing(undefined)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><form onSubmit={(event) => { event.preventDefault(); save(new FormData(event.currentTarget)); }}><DialogHeader><DialogTitle>{editing ? "Edit promotion" : "New promotion"}</DialogTitle><DialogDescription>Percentage values use normal percentages. Fixed, minimum, and shipping amounts use minor currency units.</DialogDescription></DialogHeader><PromotionFields promotion={editing ?? undefined} /><DialogFooter className="mt-5"><Button type="button" variant="outline" onClick={() => setEditing(undefined)}>Cancel</Button><Button disabled={pending}>Save promotion</Button></DialogFooter></form></DialogContent></Dialog></div>;
}

function PromotionFields({ promotion }: { promotion?: Promotion }) { return <div className="grid gap-4 py-5 md:grid-cols-2"><Field name="name" label="Campaign name" required defaultValue={promotion?.name} /><Field name="code" label="Coupon code" required defaultValue={promotion?.code} /><Select name="status" label="Status" value={promotion?.status ?? "draft"} options={["draft", "active", "archived"]} /><Select name="type" label="Discount type" value={promotion?.type ?? "percentage"} options={["percentage", "fixed", "free_shipping"]} /><Field name="value" label="Value (% or minor units)" type="number" min="0" step="0.01" defaultValue={promotion ? promotion.type === "percentage" ? promotion.value / 100 : promotion.value : 10} /><Field name="minimumSubtotal" label="Minimum subtotal" type="number" min="0" defaultValue={promotion?.minimumSubtotal ?? 0} /><Field name="startsAt" label="Starts at" type="datetime-local" defaultValue={dateInput(promotion?.startsAt)} /><Field name="endsAt" label="Ends at" type="datetime-local" defaultValue={dateInput(promotion?.endsAt)} /><Field name="usageLimit" label="Total usage limit" type="number" min="1" defaultValue={promotion?.usageLimit ?? ""} /><Field name="perCustomerLimit" label="Per-customer limit" type="number" min="1" defaultValue={promotion?.perCustomerLimit ?? ""} /><Field name="productIds" label="Eligible product IDs" defaultValue={listValue(promotion?.productIds)} placeholder="12, 18, 24" /><Field name="categories" label="Eligible categories" defaultValue={listValue(promotion?.categories)} placeholder="Clothing, Accessories" /><label className="flex items-center gap-2 text-sm font-medium md:col-span-2"><input name="firstOrderOnly" type="checkbox" defaultChecked={promotion?.firstOrderOnly} />First order only</label></div>; }
function Field({ name, label, ...props }: React.ComponentProps<typeof Input> & { name: string; label: string }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} {...props} /></div>; }
function Select({ name, label, value, options }: { name: string; label: string; value: string; options: string[] }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><select id={name} name={name} defaultValue={value} className="w-full rounded-md border bg-background px-3 py-2 text-sm">{options.map((option) => <option key={option} value={option}>{option.replace("_", " ")}</option>)}</select></div>; }
function listValue(raw?: string | null) { try { const value = JSON.parse(raw ?? "[]"); return Array.isArray(value) ? value.join(", ") : ""; } catch { return ""; } }
function dateInput(value?: string | null) { return value ? value.slice(0, 16) : ""; }
function promotionLabel(promotion: Promotion) { if (promotion.type === "percentage") return `${promotion.value / 100}% off`; if (promotion.type === "fixed") return `${promotion.value} off`; return "Free shipping"; }
function scheduleLabel(promotion: Promotion) { if (!promotion.startsAt && !promotion.endsAt) return "Always"; return `${promotion.startsAt ? new Date(promotion.startsAt).toLocaleDateString() : "Now"} - ${promotion.endsAt ? new Date(promotion.endsAt).toLocaleDateString() : "No end"}`; }
